// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgverCjzh5LkZJnjSJ7U4YSkyaSTTdiGE',
    appId: '1:494525372299:web:4d144a9540d79fc7f2418e',
    messagingSenderId: '494525372299',
    projectId: 'mynotes-flutter-01292024',
    authDomain: 'mynotes-flutter-01292024.firebaseapp.com',
    storageBucket: 'mynotes-flutter-01292024.appspot.com',
    measurementId: 'G-CZR4JQXEXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk2tyh-WD32UJl6N9TyuBXcL7OzbuaJR8',
    appId: '1:494525372299:android:149b4fde662c6524f2418e',
    messagingSenderId: '494525372299',
    projectId: 'mynotes-flutter-01292024',
    storageBucket: 'mynotes-flutter-01292024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVhud-KSDt8NQNyBY7hQkqQ-q79eh_4Lc',
    appId: '1:494525372299:ios:9f87686fdb59b119f2418e',
    messagingSenderId: '494525372299',
    projectId: 'mynotes-flutter-01292024',
    storageBucket: 'mynotes-flutter-01292024.appspot.com',
    iosBundleId: 'com.flutterproject.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVhud-KSDt8NQNyBY7hQkqQ-q79eh_4Lc',
    appId: '1:494525372299:ios:be00d8500eb6cbfdf2418e',
    messagingSenderId: '494525372299',
    projectId: 'mynotes-flutter-01292024',
    storageBucket: 'mynotes-flutter-01292024.appspot.com',
    iosBundleId: 'com.flutterproject.mynotes.RunnerTests',
  );
}
